//SAMPLE
//THIS FILE IS DYNAMICALLY GENERATED BY testwriter.js
import static javaly.Test.*;

public class StagingMethodTest{

  public static void main(String[] args){
    //prep code
    //...
    
    assertEquals(3, new MethodHolder().add(1, 2));

    assertEquals(2, new MethodHolder().add(1, 1));

    assertEquals(4, new MethodHolder().add(2, 2));

    printResults();
  }


}
